### ISSUE TITLE
Authorization Issue & Plugin Missing from Plugin Store

### ISSUE THREAD

**Issue by martalimatyas** [askthecode/askthecode.github.io#1]
Hello,

I recently faced an authorization error with AskTheCode. I uninstalled the plugin to try a reinstallation fix, but couldn't find it in the plugin store anymore.

**Steps to reproduce:**
1. Use AskTheCode.
2. Encounter authorization error.
3. Uninstall.
4. Plugin missing from store.

**Context:**
- Ubuntu 22.04, Firefox (snap)
- Noticed other users reported similar issues for other plugins.

Can you advise on this or provide an update on the plugin's availability? Thanks!

**Comment by wuxi889** [comment]
same problem

**Comment by dsomok** [comment]
Hey @martalimatyas @wuxi889

Thank you for reaching out and sorry for the inconvenience. 

The plugin is currently undergoing a review due to the release of a new version. As per OpenAI's policies, when a new version of a plugin is under review, it becomes temporarily unavailable in the store.

Hopefully the review will be completed today, and the plugin will be available again shortly thereafter.

**Comment by dsomok** [comment]
@martalimatyas @wuxi889

The new version has been approved and the plugin is now available in the store :)
