### ISSUE TITLE
It does not seem to be able to fetch .json files 

### ISSUE THREAD

**Issue by danalex7212** [askthecode/askthecode.github.io#4]
I tried it in UPS repository at https://github.com/UPS-API/api-documentation
Its always giving the feedback 
I apologize, but it seems I encountered an issue while trying to fetch the content of the "Shipping.json" file.

**Comment by dsomok** [comment]
Hi @danalex7212,

The plugin supports .json files, however, there's a limitation on the response size that ChatGPT can handle for the plugin endpoints. The maximum response size is set to 100,000 characters, and the plugin reserves 5,000 characters for its own needs. This means the effective maximum response size is 95,000 characters.

The "Shipping.json" file you mentioned contains 461,301 characters, which exceeds this limit. That's why the plugin is unable to return its content.
